/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewTransitionIndexRouteImport } from './routes/viewTransition/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewTransitionIndexRoute = ViewTransitionIndexRouteImport.update({
  id: '/viewTransition/',
  path: '/viewTransition/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/viewTransition/': typeof ViewTransitionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/viewTransition': typeof ViewTransitionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/viewTransition/': typeof ViewTransitionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/viewTransition/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/viewTransition'
  id: '__root__' | '/' | '/viewTransition/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ViewTransitionIndexRoute: typeof ViewTransitionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewTransition/': {
      id: '/viewTransition/'
      path: '/viewTransition'
      fullPath: '/viewTransition/'
      preLoaderRoute: typeof ViewTransitionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ViewTransitionIndexRoute: ViewTransitionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
