/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FragmentRefsIndexRouteImport } from './routes/fragmentRefs/index'
import { Route as ViewTransitionIndexRouteImport } from './routes/viewTransition/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FragmentRefsIndexRoute = FragmentRefsIndexRouteImport.update({
  id: '/fragmentRefs/',
  path: '/fragmentRefs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewTransitionIndexRoute = ViewTransitionIndexRouteImport.update({
  id: '/viewTransition/',
  path: '/viewTransition/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fragmentRefs/': typeof FragmentRefsIndexRoute
  '/viewTransition/': typeof ViewTransitionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fragmentRefs': typeof FragmentRefsIndexRoute
  '/viewTransition': typeof ViewTransitionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fragmentRefs/': typeof FragmentRefsIndexRoute
  '/viewTransition/': typeof ViewTransitionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fragmentRefs/' | '/viewTransition/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fragmentRefs' | '/viewTransition'
  id: '__root__' | '/' | '/fragmentRefs/' | '/viewTransition/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FragmentRefsIndexRoute: typeof FragmentRefsIndexRoute
  ViewTransitionIndexRoute: typeof ViewTransitionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragmentRefs/': {
      id: '/fragmentRefs/'
      path: '/fragmentRefs'
      fullPath: '/fragmentRefs/'
      preLoaderRoute: typeof FragmentRefsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewTransition/': {
      id: '/viewTransition/'
      path: '/viewTransition'
      fullPath: '/viewTransition/'
      preLoaderRoute: typeof ViewTransitionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FragmentRefsIndexRoute: FragmentRefsIndexRoute,
  ViewTransitionIndexRoute: ViewTransitionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
